ip_addresses:
  local_host: "opc.tcp://192.168.0.1:4840"
  cognex_linescan: "opc.tcp://192.168.54.11:4840"
  crc_opc: "ocp.tcp://192.168.54.15:4840"

timeouts:
    default: 10000

nodes:
#CRC
  traveler_id: ns=4;i=74
  part_count: ns=4;i=75
  total_part_count: ns=4;i=42
  top_heater_SV: ns=4;i=65
  top_heater_PV: ns=4;i=68
  top_heater_enable: ns=4;i=53
  bottom_heater_SV: ns=4;i=66
  bottom_heater_PV: ns=4;i=67
  bottom_heater_enable: ns=4;i=69
  cooling_fans: ns=4;i=56
  line_speed: ns=4;i=52
  waste_tension: ns=4;i=63
  feed_tension: ns=4;i=58
  roll_diameter: ns=4;i=70
  start_mode: ns=4;i=64
  slow_start_mode: ns=4;i=60
  stop_mode: ns=4;i=61
  jog_mode: ns=4;i=57
  safety_ok: ns=4;i=59
  system_enable: ns=4;i=62
  waste_tension_enable: ns=4;i=76
  feed_tension_enable: ns=4;i=77

##linescan
#    part_count: ns=2;s=Part_Count
#    job_number: ns=2;s=Job_Number
#    count_of_blobs: ns=2;s=Count_of_Blobs
#    part_width: ns=2;s=Part_Width
#    histogram_avg: ns=2;s=Histogram_Avg
#    histogram_contrast: ns=2;s=Histogram_Contrast
#    job_active: ns=2;s=Job_Active
#    write_ok: ns=2;s=Write_OK
#    too_many_blobs: ns=2;s=Too_Many_Blobs
#    really_big_blob: ns=2;s=Really_Big_Blob
#    too_many_big_blobs: ns=2;s=Too_Many_Big_Blobs


